---
title: Trend of Non Working population in Australia by State
author: Echo
date: 2021-11-15T07:00:00
slug: []
categories: []
meta_img: images/image.png
description: Description for the page
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r}
library(plotly) 
library(tidyverse)

population = read.csv("state.csv")
population = population %>% 
    filter(LABEL != "Australia") %>% 
    mutate(`Under 15` = X0.14,
           `Working Population` = Working) %>% 
    mutate(`Over 64` = 100 - `Under 15` - `Working Population`) %>% 
    mutate(YEAR = as.factor(YEAR))
population1 = population %>% 
    select(LABEL, YEAR, `Under 15`) %>% 
    pivot_wider(names_from = LABEL, values_from = `Under 15`)
population2 = population %>% 
    select(LABEL, YEAR, `Over 64`) %>% 
    pivot_wider(names_from = LABEL, values_from = `Over 64`)
```


#### Under 15

```{r}
options(warn = -1)
fig <- plot_ly(population1, x = ~YEAR, y = ~`New South Wales`, name = "New South Wales", type = 'scatter', mode = 'lines') 

for (n in names(population1)[3:9]) {
    fig = fig %>% add_trace(y = population1[[n]], name = n, mode = 'lines+markers')
}

fig <- fig %>%
  layout(showlegend = T,
         xaxis = list(title = 'Year'), 
         yaxis = list(title = 'Working age population (%)'),
         legend = list(orientation = "h",   # show entries horizontally
                     xanchor = "center",  # use center of legend as anchor
                     x = 0.5, y=-0.2))

fig
```


#### Over 64

```{r}
options(warn = -1)
fig <- plot_ly(population2, x = ~YEAR, y = ~`New South Wales`, name = "New South Wales", type = 'scatter', mode = 'lines') 

for (n in names(population2)[3:9]) {
    fig = fig %>% add_trace(y = population2[[n]], name = n, mode = 'lines+markers')
}

fig <- fig %>%
  layout(showlegend = T,
         xaxis = list(title = 'Year'), 
         yaxis = list(title = 'Working age population (%)'),
         legend = list(orientation = "h",   # show entries horizontally
                     xanchor = "center",  # use center of legend as anchor
                     x = 0.5, y=-0.2))

fig
```
