---
title: World GDP Growth in 2016
author: Echo
date: 2021-11-15T12:00:00
slug: []
categories: []
meta_img: images/image.png
description: Description for the page
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(highcharter) 
library(tidyverse)
library(readr)
library(maps)

gdp = read.csv("GDP.csv", skip = 4)
gdp = gdp %>% select(1,2,5:65) %>% pivot_longer(cols = X1960:X2020, names_to='year', values_to='gdp')
gdp = gdp %>% 
    mutate(year = as.numeric(str_extract(year, "[0-9]+"))) %>% 
    filter(year == 2016)
```

```{r}
dat <- iso3166
dat <- rename(dat, "iso-a3" = a3)
dat = inner_join(dat, gdp %>% select(Country.Code, gdp) %>% rename("iso-a3" = Country.Code))
```

In 2016, Australia is the #44 of all countries and regions in GDP growth. 

```{r}
hcmap(
    map = "custom/world-highres3", # high resolution world map
    data = dat, # name of dataset
    joinBy = "iso-a3",
    value = "gdp",
    name = "GDP growth (annual %)", 
    showInLegend = TRUE, # hide legend
    nullColor = "#DADADA",
    download_map_data = TRUE
) %>%
    hc_mapNavigation(enabled = TRUE) 
```

